runtime: python
env: flex
entrypoint: gunicorn -b :$PORT djangoProject.wsgi --timeout 90

beta_settings:
    cloud_sql_instances: online-gift-shop-350507:australia-southeast1:giftshop

runtime_config:
  python_version: 3

handlers:
- url: /static
  static_dir: /static

- url: /common_static
  static_dir: /common_static

- url: .*
  script: djangoproject.wsgi.application
