# Generated by Django 4.0.3 on 2022-03-20 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftshoptest', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customerInfo',
        ),
    ]
