# Generated by Django 4.0.3 on 2022-03-20 12:34

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('giftshoptest', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('adid', models.IntegerField(primary_key=True, serialize=False)),
                ('adminname', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Orderid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('date', models.DateField(null=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('emailaddress', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Productid', models.IntegerField(primary_key=True, serialize=False)),
                ('Productname', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('Price', models.IntegerField()),
                ('information', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='')),
            ],
        ),
    ]
