# Generated by Django 4.0.3 on 2022-03-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftshoptest', '0008_admin_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='emailaddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
