# Generated by Django 4.0.3 on 2022-03-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftshoptest', '0009_customerinfo_emailaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
